version: "3.8"

services:
  database:
    restart: "always"
    image: "linuxserver/mariadb"
    container_name: mariadb
    environment:
      - PUID=1009
      - PGID=1009
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - TZ=Europe/Berlin
    ports:
      - "3306:3306"
    volumes:
      - "/01_data/persistent/mysql:/config"
    networks:
      - mariadb_net
    logging:
      options:
        max-size: "128m"
        max-files: "3"

networks:
  mariadb_net:
    external: true
